### PR TITLE
fix: Misspelled name

### PR DESCRIPTION
**Pull request by ThePrimeagen**
Also cleaning up trailing whitespace, a bad practice

### CODE REVIEW

**Comment by piq9117** [comment]
LGTM

**Comment by opti21** [comment]
needs more "fucks"

**Comment by brandoncc** [comment]
That high praise definitely needs to go to the correct person, +1 for this PR

**Comment by acicco** [comment]
*mic drop* +100XP

**Review by eruizc-dev — APPROVED** [review]

**Review by opti21 — APPROVED** [review]

**Review by brandoncc — APPROVED** [review]

**Review by SimeonAleksov — APPROVED** [review]

**Review by piq9117 — APPROVED** [review]

**Review by rtrom — APPROVED** [review]

**Comment by jsatk** [comment]
LGTM!

**Review by jsatk — APPROVED** [review]
Great work!

**Review by strager — APPROVED** [review]

**Review by acicco — APPROVED** [review]
Insightful

**Review by luigibertaco — APPROVED** [review]
🚀

**Review by trewjames — APPROVED** [review]

**Review by scrap — APPROVED** [review]
This looks amazing ⭐

**Review by rwxrob — APPROVED** [review]

**Review by rwxrob — APPROVED** [review]

**Comment by ellisonleao** [comment]
Praise open source community

**Comment by yonikosiner** [comment]
Interesting...

**Comment by cchampou** [comment]
> What is the purpose of the duplication? Shouldn't it be
> `have nothing against the *people* there (except ThePrimeagen who is a fucking uninformed, script-kiddy dick).`
> ?

Spent 30 minutes trying to understand... Can someone explain 🙏

**Comment by strager** [comment]
> What is the purpose of the duplication? Shouldn't it be
> `have nothing against the *people* there (except ThePrimeagen who is a fucking uninformed, script-kiddy dick).`
> ?

ThePrimeagen forgot to write tests.

**Comment by trewjames** [comment]
> > What is the purpose of the duplication? Shouldn't it be
> > `have nothing against the *people* there (except ThePrimeagen who is a fucking uninformed, script-kiddy dick).`
> > ?
> 
> ThePrimeagen forgot to write tests.

classic typescript, <C-c> neo-alpha-vim using script-kiddy behavior smh.

**Pull request merged**
