### PR TITLE
Grammar corrections and also making your love letter more obvious

### PR DESCRIPTION
**Pull request by wijiler**
make sure to pay him thousands more dollars

### CODE REVIEW

**Comment by wijiler** [comment]
remember these are very necessary imrpovements

**Comment by rwxrob** [comment]
My God you are stupid. You proved it objectively over and over. You don't realize how much you are confirming every one of my claims that started this whole thing. By the way, 'en mass' is correct, dumb ass.

**Comment by wijiler** [comment]
En masse* https://brians.wsu.edu/2016/05/24/in-mass/

**Comment by wijiler** [comment]
But you trying to make it fancy makes it seem like your still in fifth grade

**Comment by wijiler** [comment]
You would fit in really well on stackoverflow

**Comment by rwxrob** [comment]
I speak fluent French and lived there for two years. It frequently comes out in my regular communication. Tell you what. I'll italicize it and change it to *en masse* so idiots like you don't get confused.

**Comment by rwxrob** [comment]
When can we expect you to produce any content of actual value? We all laughed our asses off at your Rust project.

**Pull request closed without merging**
